import React from 'react';
import Card from './ui/Card';
import Table, { TableRow, TableCell } from './ui/Table';
import PrimaryButton from './ui/PrimaryButton';
import BrandHeader from './BrandHeader';
import Spinner from './ui/Spinner';

const InvoicePreviewCard = ({ previews, totals, onConfirm, isSubmitting }) => {
    if (!previews || previews.length === 0) return <div>No items to bill.</div>;

    return (
        <div className="space-y-6">
            <Card className="bg-white">
                <div className="p-4 border-b border-gray-100">
                    <BrandHeader showRole={false} />
                    <div className="flex justify-between items-end mt-4 text-sm text-gray-600">
                        <div>
                            <p><strong>Invoice Date:</strong> {new Date().toLocaleDateString()}</p>
                            <p><strong>Generated By:</strong> Lalchand Traders System</p>
                        </div>
                        <div className="text-right">
                            <p>Address: [Address Placeholder]</p>
                        </div>
                    </div>
                </div>

                <div className="flex flex-col lg:flex-row gap-6 p-4">
                    {/* Table Section */}
                    <div className="flex-1">
                        <h3 className="text-lg font-medium text-gray-900 mb-4">Items to Bill</h3>
                        <Table headers={['Customer', 'Medium', 'Super Small', 'Subtotal', 'GST (5%)', 'Total']}>
                            {previews.map((item, index) => (
                                <TableRow key={index}>
                                    <TableCell className="font-medium text-gray-900">{item.customer_name}</TableCell>
                                    <TableCell className="text-right">{item.medium_bags}</TableCell>
                                    <TableCell className="text-right">{item.super_small_bags}</TableCell>
                                    <TableCell className="text-right">₹{item.subtotal.toFixed(2)}</TableCell>
                                    <TableCell className="text-right text-gray-600">₹{(item.sgst_amount + item.cgst_amount).toFixed(2)}</TableCell>
                                    <TableCell className="text-right font-bold text-gray-900">₹{item.total_amount.toFixed(2)}</TableCell>
                                </TableRow>
                            ))}
                        </Table>
                    </div>

                    {/* Summary Section */}
                    <div className="w-full lg:w-80">
                        <div className="bg-gray-50 rounded-lg p-4 border border-gray-200 sticky top-6">
                            <h4 className="font-medium text-gray-900 mb-3 border-b pb-2">Billing Summary</h4>
                            <div className="space-y-3 text-sm">
                                <div className="flex justify-between py-1">
                                    <span className="text-gray-600">Subtotal</span>
                                    <span className="font-medium">₹{totals.subtotal.toFixed(2)}</span>
                                </div>
                                <div className="flex justify-between py-1 text-orange-600 bg-orange-50 px-2 rounded">
                                    <span>SGST (2.5%)</span>
                                    <span>₹{totals.sgst.toFixed(2)}</span>
                                </div>
                                <div className="flex justify-between py-1 text-orange-600 bg-orange-50 px-2 rounded">
                                    <span>CGST (2.5%)</span>
                                    <span>₹{totals.cgst.toFixed(2)}</span>
                                </div>
                                <div className="border-t border-gray-300 pt-4 mt-2 flex justify-between items-center">
                                    <span className="font-bold text-lg text-gray-900">Grand Total</span>
                                    <span className="font-bold text-xl text-primary">₹{totals.total.toFixed(2)}</span>
                                </div>
                            </div>

                            <div className="mt-6">
                                <PrimaryButton
                                    onClick={onConfirm}
                                    disabled={isSubmitting}
                                    className="w-full"
                                >
                                    {isSubmitting ? <><Spinner size="sm" color="white" /><span className="ml-2">Processing...</span></> : 'CONFIRM & GENERATE'}
                                </PrimaryButton>
                                <p className="text-xs text-gray-500 text-center mt-3">
                                    This action will generate permanent invoices.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </Card>
        </div>
    );
};

export default InvoicePreviewCard;
